apiVersion: v1
kind: Service
metadata:
  name: cafestatic-recreate-service
  labels:
    app: cafestatic
spec:
  type: NodePort
  selector:
    app: cafestatic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
